### ISSUE TITLE
Fixup 0862fd2

### ISSUE THREAD

**Issue by mawi12345** [julien-c/epub#11]
`npm install epub --no-optional` downloads the tag `v0.1.5`. 

please publish a version with https://github.com/julien-c/epub/commit/87388fd80cf98ddb19483759e589d8142e7f2db1 (Fixup)

thx, great work

**Comment by julien-c** [comment]
```bash
$ npm version patch
$ npm publish
```

You should be good to go!

Thanks for reporting.
