### ISSUE TITLE
Add callbacks

### ISSUE THREAD

**Issue by mawi12345** [julien-c/epub#14]
I am currently refactoring the whole lib to add callbacks.
One big benefit of this the the methods are now decoupled (`getMimeType` does not call `getRootFiles`...)

I have done this to be able to unit test one method (preparation for the xml2js option update).

Please have a look at https://github.com/mawi12345/epub/commit/a20e6fd4c52055f668989822bdc3037c40a6d373 and let me know what you think about the changes.

**Comment by julien-c** [comment]
Sorry for the late response @mawi12345 – yes, this makes sense.
