### ISSUE TITLE
TypeScript definition errors

### ISSUE THREAD

**Issue by andy-ms** [julien-c/epub#30]
* The type definition `epub.d.ts` contains `/// <reference path="../node/node.d.ts" />`, but that won't exist if installing normally via `npm`. `/// <reference types="node" />` would work better. Note there should also be a dependency on the npm package `@types/node` or that won't work either.
* Instead of `declare module "epub" { ... }`, it would be better to write everything directly at the top-level (by simply removing that wrapper) so this file can be imported.

**Comment by xavdid** [comment]
@andy-ms this should be fixed now!
